### PR TITLE
Added entries for SimpleImageButton and RainbowLoading.Forms

### PR DESCRIPTION
**Pull request by mariusmuntean**
I added entries for two of my Xamarin.Forms projects.

One is a customizable Xamarin.Forms ImageButton. Not another one, right? But it is quite simple to use and supports many platforms.
The second project is a SkiaSharp implementation of the material design loading indicator. This one's also customizable to better match any corporate design.

Both projects are available on NuGet.org as well and they have nice sample projects to get a good idea of what you'll get.

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Thanks!. Recently I added **RainbowLoading.Forms** and we have a conflict here. Could you apply changes to just add **SimpleImageButton**?

**Comment by mariusmuntean** [comment]
Hi @jsuarezruiz 
I removed the entry for **RainbowLoading.Forms**

**Review by jsuarezruiz — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
Thanks!

**Comment by mariusmuntean** [comment]
Thank you as well!

**Pull request merged**
